// This code was generated by Hypar.
// Edits to this code will be overwritten the next time code generation occurs.
// DO NOT EDIT THIS FILE.
using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Facade
{
	public class FacadeOutputs: ResultsBase
	{
		/// <summary>
		/// Total facade paenls.
		/// </summary>
		[JsonProperty("Panel Quantity")]
		public double PanelQuantity {get;}


		
		/// <summary>
		/// Construct a FacadeOutputs with default inputs.
		/// This should be used only for testing.
		/// </summary>
		public FacadeOutputs() : base()
		{

		}
		
		/// <summary>
		/// Construct a FacadeOutputs specifying all inputs.
		/// </summary>
		/// <returns></returns>
		[JsonConstructor]
		public FacadeOutputs(double panelquantity): base()
		{
			this.PanelQuantity = panelquantity;

		}
	}
}