//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.1.21.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------
using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Elements.Geometry.Solids;
using Elements.Spatial;
using Elements.Validators;
using Elements.Serialization.JSON;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using Line = Elements.Geometry.Line;
using Polygon = Elements.Geometry.Polygon;

namespace Elements
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ViewScopeClippingBehavior
    {
        [System.Runtime.Serialization.EnumMember(Value = @"All")]
        All = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = @"TopAndBottom")]
        TopAndBottom = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Top")]
        Top = 2,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Bottom")]
        Bottom = 3,
    
        [System.Runtime.Serialization.EnumMember(Value = @"FrontAndBack")]
        FrontAndBack = 4,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Front")]
        Front = 5,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Back")]
        Back = 6,
    
        [System.Runtime.Serialization.EnumMember(Value = @"LeftAndRight")]
        LeftAndRight = 7,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Left")]
        Left = 8,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Right")]
        Right = 9,
    
    }
}