// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Elements.Geometry.Solids;
using Elements.Validators;
using Elements.Serialization.JSON;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using System;
using System.Collections.Generic;
using System.Linq;
using Line = Elements.Geometry.Line;
using Polygon = Elements.Geometry.Polygon;

namespace CoreBySketch
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v12.0.0.0)")]
    
    public  class CoreBySketchInputs : S3Args
    
    {
        [Newtonsoft.Json.JsonConstructor]
        
        public CoreBySketchInputs(IList<Polygon> @perimeters, double @heightAboveRoof, string bucketName, string uploadsBucket, Dictionary<string, string> modelInputKeys, string gltfKey, string elementsKey, string ifcKey):
        base(bucketName, uploadsBucket, modelInputKeys, gltfKey, elementsKey, ifcKey)
        {
            var validator = Validator.Instance.GetFirstValidatorForType<CoreBySketchInputs>();
            if(validator != null)
            {
                validator.PreConstruct(new object[]{ @perimeters, @heightAboveRoof});
            }
        
            this.Perimeters = @perimeters;
            this.HeightAboveRoof = @heightAboveRoof;
        
            if(validator != null)
            {
                validator.PostConstruct(this);
            }
        }
    
        /// <summary>List of perimeters of the buildings service cores.</summary>
        [Newtonsoft.Json.JsonProperty("Perimeters", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public IList<Polygon> Perimeters { get; set; }
    
        /// <summary>The projection of the service core above the highest building level.</summary>
        [Newtonsoft.Json.JsonProperty("HeightAboveRoof", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Range(0D, double.MaxValue)]
        public double HeightAboveRoof { get; set; } = 2D;
    
    
    }
}