// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace ColumnsByFloors
{
    public class ColumnsByFloorsOutputs: ResultsBase
    {
		/// <summary>
		/// Total quantity of columns.
		/// </summary>
		[JsonProperty("Column Quantity")]
		public double ColumnQuantity {get;}


        
        /// <summary>
        /// Construct a ColumnsByFloorsOutputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public ColumnsByFloorsOutputs() : base()
        {

        }


        /// <summary>
        /// Construct a ColumnsByFloorsOutputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public ColumnsByFloorsOutputs(double columnquantity): base()
        {
			this.ColumnQuantity = columnquantity;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}