// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Elements.Geometry.Solids;
using Elements.Validators;
using Elements.Serialization.JSON;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Hypar.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using Line = Elements.Geometry.Line;
using Polygon = Elements.Geometry.Polygon;

namespace RoomsByLevels
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v12.0.0.0)")]
    
    public  class RoomsByLevelsInputs : S3Args
    
    {
        [Newtonsoft.Json.JsonConstructor]
        
        public RoomsByLevelsInputs(double @corridorWidth, double @roomArea, string bucketName, string uploadsBucket, Dictionary<string, string> modelInputKeys, string gltfKey, string elementsKey, string ifcKey):
        base(bucketName, uploadsBucket, modelInputKeys, gltfKey, elementsKey, ifcKey)
        {
            var validator = Validator.Instance.GetFirstValidatorForType<RoomsByLevelsInputs>();
            if(validator != null)
            {
                validator.PreConstruct(new object[]{ @corridorWidth, @roomArea});
            }
        
            this.CorridorWidth = @corridorWidth;
            this.RoomArea = @roomArea;
        
            if(validator != null)
            {
                validator.PostConstruct(this);
            }
        }
    
        /// <summary>Width of the corridor.</summary>
        [Newtonsoft.Json.JsonProperty("Corridor Width", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Range(1.7D, 4.0D)]
        public double CorridorWidth { get; set; } = 2.8000000000000003D;
    
        /// <summary>Desired area of each room.</summary>
        [Newtonsoft.Json.JsonProperty("Room Area", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Range(20.0D, 200.0D)]
        public double RoomArea { get; set; } = 110D;
    
    }
}