// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace RoomsByLevels
{
    public class RoomsByLevelsOutputs: SystemResults
    {
		/// <summary>
		/// Quantity of Rooms on each floor.
		/// </summary>
		[JsonProperty("Rooms Per Floor")]
		public double RoomsPerFloor {get; set;}

		/// <summary>
		/// Quantity of Rooms in the building.
		/// </summary>
		[JsonProperty("Room Total")]
		public double RoomTotal {get; set;}



        /// <summary>
        /// Construct a RoomsByLevelsOutputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public RoomsByLevelsOutputs() : base()
        {

        }


        /// <summary>
        /// Construct a RoomsByLevelsOutputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public RoomsByLevelsOutputs(double roomsPerFloor, double roomTotal): base()
        {
			this.RoomsPerFloor = roomsPerFloor;
			this.RoomTotal = roomTotal;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}