// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Amazon;
using Amazon.Lambda.Core;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using System.Threading.Tasks;

[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.Json.JsonSerializer))]
namespace FloorsByLevels
{
    public class Function
    {
        // Cache the model store for use by subsequent
        // executions of this lambda.
        private IModelStore<FloorsByLevelsInputs> store;

        public async Task<FloorsByLevelsOutputs> Handler(FloorsByLevelsInputs args, ILambdaContext context)
        {
            if(this.store == null)
            {
                this.store = new S3ModelStore<FloorsByLevelsInputs>(RegionEndpoint.USWest1);
            }
            
            var l = new InvocationWrapper<FloorsByLevelsInputs,FloorsByLevelsOutputs>(store, FloorsByLevels.Execute);
            var output = await l.InvokeAsync(args);
            return output;
        }
      }
}