// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace PlansByFloors
{
    public class PlansByFloorsInputs: S3Args
    {
		/// <summary>
		/// Quantity of rooms on the ground floor.
		/// </summary>
		[JsonProperty("Ground Floor Rooms")]
		public double GroundFloorRooms {get;}

		/// <summary>
		/// Quantity of rooms on a typical floor.
		/// </summary>
		[JsonProperty("Typical Rooms Per Upper Floor")]
		public double TypicalRoomsPerUpperFloor {get;}

		/// <summary>
		/// Minimum area for each room.
		/// </summary>
		[JsonProperty("Minimum Room Area")]
		public double MinimumRoomArea {get;}


        
        /// <summary>
        /// Construct a PlansByFloorsInputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public PlansByFloorsInputs() : base()
        {
			this.GroundFloorRooms = 20;
			this.TypicalRoomsPerUpperFloor = 20;
			this.MinimumRoomArea = 10;

        }


        /// <summary>
        /// Construct a PlansByFloorsInputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public PlansByFloorsInputs(double groundfloorrooms, double typicalroomsperupperfloor, double minimumroomarea, string bucketName, string uploadsBucket, Dictionary<string, string> modelInputKeys, string gltfKey, string elementsKey, string ifcKey): base(bucketName, uploadsBucket, modelInputKeys, gltfKey, elementsKey, ifcKey)
        {
			this.GroundFloorRooms = groundfloorrooms;
			this.TypicalRoomsPerUpperFloor = typicalroomsperupperfloor;
			this.MinimumRoomArea = minimumroomarea;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}