// This code was generated by Hypar.
// Edits to this code will be overwritten the next time code generation occurs.
// DO NOT EDIT THIS FILE.
using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Mass
{
	public class MassOutputs: ResultsBase
	{
		/// <summary>
		/// Height of the building.
		/// </summary>
		[JsonProperty("Height")]
		public double Height {get;}

		/// <summary>
		/// Depth of the subgrade section.
		/// </summary>
		[JsonProperty("Subgrade")]
		public double Subgrade {get;}

		/// <summary>
		/// Vertical distance between setbacks.
		/// </summary>
		[JsonProperty("Interval")]
		public double Interval {get;}

		/// <summary>
		/// Setback offset from previous interval.
		/// </summary>
		[JsonProperty("Setback")]
		public double Setback {get;}

		/// <summary>
		/// Building envelope volume including subgrade section.
		/// </summary>
		[JsonProperty("Volume")]
		public double Volume {get;}


		
		/// <summary>
		/// Construct a MassOutputs with default inputs.
		/// This should be used only for testing.
		/// </summary>
		public MassOutputs() : base()
		{

		}
		
		/// <summary>
		/// Construct a MassOutputs specifying all inputs.
		/// </summary>
		/// <returns></returns>
		[JsonConstructor]
		public MassOutputs(double height, double subgrade, double interval, double setback, double volume): base()
		{
			this.Height = height;
			this.Subgrade = subgrade;
			this.Interval = interval;
			this.Setback = setback;
			this.Volume = volume;

		}
	}
}