//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.1.21.0 (Newtonsoft.Json v12.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------
using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Elements.Geometry.Solids;
using Elements.Spatial;
using Elements.Validators;
using Elements.Serialization.JSON;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using Line = Elements.Geometry.Line;
using Polygon = Elements.Geometry.Polygon;

namespace Elements
{
    #pragma warning disable // Disable all warnings

    /// <summary>Represents a single room.</summary>
    [JsonConverter(typeof(Elements.Serialization.JSON.JsonInheritanceConverter), "discriminator")]
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class Room : GeometricElement
    {
        [JsonConstructor]
        public Room(Polygon @perimeter, string @suiteName, string @suiteNumber, string @department, double @number, double @designArea, double @designRatio, Transform @transform = null, Material @material = null, Representation @representation = null, bool @isElementDefinition = false, System.Guid @id = default, string @name = null)
            : base(transform, material, representation, isElementDefinition, id, name)
        {
            this.Perimeter = @perimeter;
            this.SuiteName = @suiteName;
            this.SuiteNumber = @suiteNumber;
            this.Department = @department;
            this.Number = @number;
            this.DesignArea = @designArea;
            this.DesignRatio = @designRatio;
            }
        
        // Empty constructor
        public Room()
            : base()
        {
        }
    
        /// <summary>The boundary of the room</summary>
        [JsonProperty("Perimeter", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Polygon Perimeter { get; set; }
    
        /// <summary>Name of the suite assigned to the room.</summary>
        [JsonProperty("Suite Name", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string SuiteName { get; set; }
    
        /// <summary>Number of the suite assigned to the room.</summary>
        [JsonProperty("Suite Number", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string SuiteNumber { get; set; }
    
        /// <summary>Name of the department assigned to the room.</summary>
        [JsonProperty("Department", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Department { get; set; }
    
        /// <summary>The number of the room.</summary>
        [JsonProperty("Number", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double Number { get; set; }
    
        /// <summary>Desired area of the room.</summary>
        [JsonProperty("Design Area", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double DesignArea { get; set; }
    
        /// <summary>Desired ratio of the X to Y dimensions of the room.</summary>
        [JsonProperty("Design Ratio", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double DesignRatio { get; set; }
    
    
    }
}