// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace FoundationByEnvelope
{
    public class FoundationByEnvelopeOutputs: ResultsBase
    {
		/// <summary>
		/// The calculated foundation depth.
		/// </summary>
		[JsonProperty("Depth")]
		public double Depth {get;}


        
        /// <summary>
        /// Construct a FoundationByEnvelopeOutputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public FoundationByEnvelopeOutputs() : base()
        {

        }


        /// <summary>
        /// Construct a FoundationByEnvelopeOutputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public FoundationByEnvelopeOutputs(double depth): base()
        {
			this.Depth = depth;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}