// This code was generated by Hypar.
// Edits to this code will be overwritten the next time code generation occurs.
// DO NOT EDIT THIS FILE.
using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Structure
{
	public class StructureOutputs: ResultsBase
	{
		/// <summary>
		/// Quantity of columns.
		/// </summary>
		[JsonProperty("Colums")]
		public double Colums {get;}


		
		/// <summary>
		/// Construct a StructureOutputs with default inputs.
		/// This should be used only for testing.
		/// </summary>
		public StructureOutputs() : base()
		{

		}
		
		/// <summary>
		/// Construct a StructureOutputs specifying all inputs.
		/// </summary>
		/// <returns></returns>
		[JsonConstructor]
		public StructureOutputs(double colums): base()
		{
			this.Colums = colums;

		}
	}
}