// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace Structure
{
    public class StructureInputs: S3Args
    {
		/// <summary>
		/// Grid interval in the X direction.
		/// </summary>
		[JsonProperty("Grid X-Axis Interval")]
		public double GridXAxisInterval {get;}

		/// <summary>
		/// Grid interval in the Y direction.
		/// </summary>
		[JsonProperty("Grid Y-Axis Interval")]
		public double GridYAxisInterval {get;}


        
        /// <summary>
        /// Construct a StructureInputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public StructureInputs() : base()
        {
			this.GridXAxisInterval = 10;
			this.GridYAxisInterval = 10;

        }


        /// <summary>
        /// Construct a StructureInputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public StructureInputs(double gridxaxisinterval, double gridyaxisinterval, string bucketName, string uploadsBucket, Dictionary<string, string> modelInputKeys, string gltfKey, string elementsKey, string ifcKey): base(bucketName, uploadsBucket, modelInputKeys, gltfKey, elementsKey, ifcKey)
        {
			this.GridXAxisInterval = gridxaxisinterval;
			this.GridYAxisInterval = gridyaxisinterval;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}