//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.1.21.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------
using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Elements.Geometry.Solids;
using Elements.Spatial;
using Elements.Validators;
using Elements.Serialization.JSON;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using Line = Elements.Geometry.Line;
using Polygon = Elements.Geometry.Polygon;

namespace Elements
{
    #pragma warning disable // Disable all warnings

    /// <summary>Represents a preset view attached to an element.</summary>
    [JsonConverter(typeof(Elements.Serialization.JSON.JsonInheritanceConverter), "discriminator")]
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ViewScope : Element
    {
        [JsonConstructor]
        public ViewScope(BBox3 @boundingBox, Camera @camera, bool? @lockRotation, bool? @clipWithBoundingBox, ViewScopeClippingBehavior? @clippingBehavior, bool? @modal, System.Collections.Generic.IDictionary<string, string> @functionVisibility, IList<object> @actions, System.Guid @id = default, string @name = null)
            : base(id, name)
        {
            this.BoundingBox = @boundingBox;
            this.Camera = @camera;
            this.LockRotation = @lockRotation;
            this.ClipWithBoundingBox = @clipWithBoundingBox;
            this.ClippingBehavior = @clippingBehavior;
            this.Modal = @modal;
            this.FunctionVisibility = @functionVisibility;
            this.Actions = @actions;
            }
        
        
        // Empty constructor
        public ViewScope()
            : base()
        {
        }
    
        /// <summary>The "focus" extent for this view.</summary>
        [JsonProperty("Bounding Box", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public BBox3 BoundingBox { get; set; }
    
        /// <summary>The camera to use for this view.</summary>
        [JsonProperty("Camera", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Camera Camera { get; set; }
    
        /// <summary>Whether this scope should lock view rotation. True to lock, False to unlock, and null to leave unchanged.</summary>
        [JsonProperty("Lock Rotation", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool? LockRotation { get; set; }
    
        /// <summary>Whether this scope should clip to the specified bounding box. If false, it only zooms to the bounding box without clipping.</summary>
        [JsonProperty("Clip With Bounding Box", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool? ClipWithBoundingBox { get; set; }
    
        /// <summary>When clipping with this box, which sides should actually do the clipping? If null, all six sides will be assumed. Front is assumed to be the side facing -Y, Top is the side facing +Z</summary>
        [JsonProperty("Clipping Behavior", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ViewScopeClippingBehavior? ClippingBehavior { get; set; }
    
        /// <summary>If true, when the user exits this scope, they'll return to their previous camera settings.</summary>
        [JsonProperty("Modal", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool? Modal { get; set; }
    
        [JsonProperty("Function Visibility", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.IDictionary<string, string> FunctionVisibility { get; set; }
    
        [JsonProperty("Actions", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public IList<object> Actions { get; set; }
    
    
    }
}