//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.1.21.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------
using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Elements.Geometry.Solids;
using Elements.Spatial;
using Elements.Validators;
using Elements.Serialization.JSON;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using Line = Elements.Geometry.Line;
using Polygon = Elements.Geometry.Polygon;

namespace Elements
{
    #pragma warning disable // Disable all warnings

    /// <summary>Represents the enclosure of mechanical system pathways.</summary>
    [JsonConverter(typeof(Elements.Serialization.JSON.JsonInheritanceConverter), "discriminator")]
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class MechanicalCorridor : GeometricElement
    {
        [JsonConstructor]
        public MechanicalCorridor(Polygon @perimeter, Vector3 @direction, double @rotation, Vector3 @start, Vector3 @end, double @length, double @volume, string @number, Transform @transform = null, Material @material = null, Representation @representation = null, bool @isElementDefinition = false, System.Guid @id = default, string @name = null)
            : base(transform, material, representation, isElementDefinition, id, name)
        {
            this.Perimeter = @perimeter;
            this.Direction = @direction;
            this.Rotation = @rotation;
            this.Start = @start;
            this.End = @end;
            this.Length = @length;
            this.Volume = @volume;
            this.Number = @number;
            }
        
        // Empty constructor
        public MechanicalCorridor()
            : base()
        {
        }
    
        /// <summary>The id of the polygon to extrude.</summary>
        [JsonProperty("Perimeter", Required = Newtonsoft.Json.Required.AllowNull)]
        public Polygon Perimeter { get; set; }
    
        /// <summary>The direction in which to extrude.</summary>
        [JsonProperty("Direction", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public Vector3 Direction { get; set; } = new Vector3();
    
        /// <summary>The rotation in degrees of the mechanical corridor.</summary>
        [JsonProperty("Rotation", Required = Newtonsoft.Json.Required.Always)]
        public double Rotation { get; set; }
    
        /// <summary>The start point of the centroid of the mechanical corridor.</summary>
        [JsonProperty("Start", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public Vector3 Start { get; set; } = new Vector3();
    
        /// <summary>The end point of the centroid of the mechanical corridor.</summary>
        [JsonProperty("End", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public Vector3 End { get; set; } = new Vector3();
    
        /// <summary>The length of the mechanical corridor.</summary>
        [JsonProperty("Length", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Range(0D, double.MaxValue)]
        public double Length { get; set; }
    
        /// <summary>The volume of the mechanical corridor.</summary>
        [JsonProperty("Volume", Required = Newtonsoft.Json.Required.Always)]
        public double Volume { get; set; }
    
        /// <summary>The number of the stair enclosure.</summary>
        [JsonProperty("Number", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Number { get; set; }
    
    
    }
}