// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Elements.Geometry.Solids;
using Elements.Validators;
using Elements.Serialization.JSON;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Hypar.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using Line = Elements.Geometry.Line;
using Polygon = Elements.Geometry.Polygon;

namespace ProgramByCSV
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v12.0.0.0)")]
    
    public  class ProgramByCSVInputs : S3Args
    
    {
        [Newtonsoft.Json.JsonConstructor]
        
        public ProgramByCSVInputs(InputData @program, bool @useImperialUnits, ProgramByCSVInputsSuiteSequence @suiteSequence, ProgramByCSVInputsRoomSequence @roomSequence, string bucketName, string uploadsBucket, Dictionary<string, string> modelInputKeys, string gltfKey, string elementsKey, string ifcKey):
        base(bucketName, uploadsBucket, modelInputKeys, gltfKey, elementsKey, ifcKey)
        {
            var validator = Validator.Instance.GetFirstValidatorForType<ProgramByCSVInputs>();
            if(validator != null)
            {
                validator.PreConstruct(new object[]{ @program, @useImperialUnits, @suiteSequence, @roomSequence});
            }
        
            this.Program = @program;
            this.UseImperialUnits = @useImperialUnits;
            this.SuiteSequence = @suiteSequence;
            this.RoomSequence = @roomSequence;
        
            if(validator != null)
            {
                validator.PostConstruct(this);
            }
        }
    
        /// <summary>A CSV list of room definitions.</summary>
        [Newtonsoft.Json.JsonProperty("Program", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public InputData Program { get; set; }
    
        /// <summary>Default is metric units.</summary>
        [Newtonsoft.Json.JsonProperty("Use imperial units", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool UseImperialUnits { get; set; }
    
        /// <summary>Changes the sequence of the suites.</summary>
        [Newtonsoft.Json.JsonProperty("Suite Sequence", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ProgramByCSVInputsSuiteSequence SuiteSequence { get; set; } = ProgramByCSVInputsSuiteSequence.Listed;
    
        /// <summary>Changes the sequence of the rooms in each suite.</summary>
        [Newtonsoft.Json.JsonProperty("Room Sequence", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ProgramByCSVInputsRoomSequence RoomSequence { get; set; } = ProgramByCSVInputsRoomSequence.Listed;
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v12.0.0.0)")]
    public enum ProgramByCSVInputsSuiteSequence
    {
        [System.Runtime.Serialization.EnumMember(Value = @"Listed")]
        Listed = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Reverse")]
        Reverse = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = @"AreaAscending")]
        AreaAscending = 2,
    
        [System.Runtime.Serialization.EnumMember(Value = @"AreaDescending")]
        AreaDescending = 3,
    
        [System.Runtime.Serialization.EnumMember(Value = @"NameAscending")]
        NameAscending = 4,
    
        [System.Runtime.Serialization.EnumMember(Value = @"NameDescending")]
        NameDescending = 5,
    
        [System.Runtime.Serialization.EnumMember(Value = @"NumberAscending")]
        NumberAscending = 6,
    
        [System.Runtime.Serialization.EnumMember(Value = @"NumberDescending")]
        NumberDescending = 7,
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v12.0.0.0)")]
    public enum ProgramByCSVInputsRoomSequence
    {
        [System.Runtime.Serialization.EnumMember(Value = @"Listed")]
        Listed = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Reverse")]
        Reverse = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = @"AreaAscending")]
        AreaAscending = 2,
    
        [System.Runtime.Serialization.EnumMember(Value = @"AreaDescending")]
        AreaDescending = 3,
    
    }
}