//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.1.21.0 (Newtonsoft.Json v12.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------
using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Elements.Geometry.Solids;
using Elements.Spatial;
using Elements.Validators;
using Elements.Serialization.JSON;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using Line = Elements.Geometry.Line;
using Polygon = Elements.Geometry.Polygon;

namespace Elements
{
    #pragma warning disable // Disable all warnings

    /// <summary>Represents an early stage building massing volume. Its boundary typically represents the nominal edge of slab, and may be articulated further by subsequent functions.</summary>
    [JsonConverter(typeof(Elements.Serialization.JSON.JsonInheritanceConverter), "discriminator")]
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class ConceptualMass : Envelope
    {
        [JsonConstructor]
        public ConceptualMass(IList<Line> @skeleton, string @primaryUseCategory, System.Guid? @building, IList<System.Guid> @levelIds, Transform @localCoordinateSystem, Profile @profile, double @elevation, double @height, Vector3 @direction, double @rotation, IList<double> @floorToFloorHeights, Transform @transform, Material @material, Representation @representation, bool @isElementDefinition, System.Guid @id, string @name)
            : base(profile, elevation, height, direction, rotation, floorToFloorHeights, transform, material, representation, isElementDefinition, id, name)
        {
            this.Skeleton = @skeleton;
            this.PrimaryUseCategory = @primaryUseCategory;
            this.Building = @building;
            this.LevelIds = @levelIds;
            this.LocalCoordinateSystem = @localCoordinateSystem;
            }
        
        // Empty constructor
        public ConceptualMass()
            : base()
        {
        }
    
        /// <summary>A collection of lines which indicate a "centerline" of the mass.</summary>
        [JsonProperty("Skeleton", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public IList<Line> Skeleton { get; set; }
    
        /// <summary>The primary programmatic use for this mass, e.g. Residential, Office, Parking, Retail. Some levels or spaces within the mass may have other uses.</summary>
        [JsonProperty("Primary Use Category", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string PrimaryUseCategory { get; set; }
    
        /// <summary>The building this mass belongs to, if any.</summary>
        [JsonProperty("Building", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Guid? Building { get; set; }
    
        /// <summary>The ids of the levels this conceptual mass contains</summary>
        [JsonProperty("Level Ids", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public IList<System.Guid> LevelIds { get; set; }
    
        /// <summary>A transform representing the local coordinate system for this mass</summary>
        [JsonProperty("Local Coordinate System", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Transform LocalCoordinateSystem { get; set; }
    
    
    }
}