// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace FloorsByEnvelope
{
    public class FloorsByEnvelopeOutputs: ResultsBase
    {
		/// <summary>
		/// Aggregate area of non-mechanical floor above grade.
		/// </summary>
		[JsonProperty("Total Rentable Floor Area")]
		public double TotalRentableFloorArea {get;}

		/// <summary>
		/// Height of the ground floor.
		/// </summary>
		[JsonProperty("Retail Floor Height")]
		public double RetailFloorHeight {get;}

		/// <summary>
		/// Height of the repeated floors.
		/// </summary>
		[JsonProperty("Repeated Floor Height")]
		public double RepeatedFloorHeight {get;}

		/// <summary>
		/// Height of the mechanical floor.
		/// </summary>
		[JsonProperty("Mechanical Floor Height")]
		public double MechanicalFloorHeight {get;}

		/// <summary>
		/// Clearance between slab edge and building envelope.
		/// </summary>
		[JsonProperty("Floor Clearance")]
		public double FloorClearance {get;}


        
        /// <summary>
        /// Construct a FloorsByEnvelopeOutputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public FloorsByEnvelopeOutputs() : base()
        {

        }


        /// <summary>
        /// Construct a FloorsByEnvelopeOutputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public FloorsByEnvelopeOutputs(double totalrentablefloorarea, double retailfloorheight, double repeatedfloorheight, double mechanicalfloorheight, double floorclearance): base()
        {
			this.TotalRentableFloorArea = totalrentablefloorarea;
			this.RetailFloorHeight = retailfloorheight;
			this.RepeatedFloorHeight = repeatedfloorheight;
			this.MechanicalFloorHeight = mechanicalfloorheight;
			this.FloorClearance = floorclearance;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}