// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Elements.Geometry.Solids;
using Elements.Validators;
using Elements.Serialization.JSON;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Hypar.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using Line = Elements.Geometry.Line;
using Polygon = Elements.Geometry.Polygon;

namespace RoofByDXF
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v13.0.0.0)")]
    
    public  class RoofByDXFInputs : S3Args
    
    {
        [Newtonsoft.Json.JsonConstructor]
        
        public RoofByDXFInputs(InputData @dXF, double @roofElevation, double @roofThickness, string bucketName, string uploadsBucket, Dictionary<string, string> modelInputKeys, string gltfKey, string elementsKey, string ifcKey):
        base(bucketName, uploadsBucket, modelInputKeys, gltfKey, elementsKey, ifcKey)
        {
            var validator = Validator.Instance.GetFirstValidatorForType<RoofByDXFInputs>();
            if(validator != null)
            {
                validator.PreConstruct(new object[]{ @dXF, @roofElevation, @roofThickness});
            }
        
            this.DXF = @dXF;
            this.RoofElevation = @roofElevation;
            this.RoofThickness = @roofThickness;
        
            if(validator != null)
            {
                validator.PostConstruct(this);
            }
        }
    
        /// <summary>DXF format closed LWPolylines representing a roof edge and openings within or aligned with the perimeter.</summary>
        [Newtonsoft.Json.JsonProperty("DXF", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public InputData DXF { get; set; }
    
        /// <summary>Roof elevation relative to the zero plane.</summary>
        [Newtonsoft.Json.JsonProperty("Roof Elevation", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Range(3.0D, 50.0D)]
        public double RoofElevation { get; set; } = 26.5D;
    
        /// <summary>Thickness of the Roof.</summary>
        [Newtonsoft.Json.JsonProperty("Roof Thickness", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Range(0.1D, 2.0D)]
        public double RoofThickness { get; set; } = 1.05D;
    
    }
}