// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace SiteBySketch
{
    public class SiteBySketchOutputs: ResultsBase
    {
		/// <summary>
		/// Area of the site.
		/// </summary>
		[JsonProperty("Area")]
		public double Area {get; set;}



        /// <summary>
        /// Construct a SiteBySketchOutputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public SiteBySketchOutputs() : base()
        {

        }


        /// <summary>
        /// Construct a SiteBySketchOutputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public SiteBySketchOutputs(double area): base()
        {
			this.Area = area;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}