// This code was generated by Hypar.
// Edits to this code will be overwritten the next time code generation occurs.
// DO NOT EDIT THIS FILE.
using Amazon;
using Amazon.Lambda.Core;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using System.Threading.Tasks;

[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.Json.JsonSerializer))]
namespace Story
{
	public class Function
	{
		// Cache the model store for use by subsequent
		// executions of this lambda.
		private IModelStore<StoryInputs> store;

		public async Task<StoryOutputs> Handler(StoryInputs args, ILambdaContext context)
		{
			if(this.store == null)
			{
				this.store = new S3ModelStore<StoryInputs>(RegionEndpoint.USWest1);
			}
			
			var l = new InvocationWrapper<StoryInputs,StoryOutputs>(store, Story.Execute);
			var output = await l.InvokeAsync(args);
			return output;
		}
  	}
}